In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("spam.csv", encoding='latin-1')

In [5]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [6]:
data['v1'] = data.v1.map({'ham':0, 'spam':1})

In [7]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,0,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,0,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,0,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,0,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,0,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,0,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,0,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,0,Rofl. Its true to its name,NaN,NaN,NaN

In [8]:
#Data Preprocessing
#'v2' column contains the text and 'v1' column contains the label
X = data['v2']
y = data['v1']

In [9]:
# Remove NaN values
import re
data.dropna(subset=['v2'])
X = data['v2']
y = data['v1']

In [10]:
#Remove integer numbers from the text

X = X.apply(lambda text: re.sub(r'\b\d+\b', '', text))

#Remove the extra spaces from dataframe
#strip() method is also applied to remove any leading or trailing spaces from the text.
X = X.apply(lambda text: re.sub(r'\s+', ' ', text.strip()))

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

# Create an instance of CountVectorizer with stop words
vector = CountVectorizer(stop_words='english')

# Fit and transform the text data
vector.fit(X)
vector.vocabulary_

{'jurong': 3659,
 'point': 5176,
 'crazy': 1706,
 'available': 706,
 'bugis': 1138,
 'great': 2969,
 'world': 7662,
 'la': 3784,
 'buffet': 1136,
 'cine': 1429,
 'got': 2929,
 'amore': 486,
 'wat': 7461,
 'ok': 4778,
 'lar': 3820,
 'joking': 3627,
 'wif': 7569,
 'oni': 4804,
 'free': 2700,
 'entry': 2310,
 'wkly': 7620,
 'comp': 1545,
 'win': 7581,
 'fa': 2440,
 'cup': 1764,
 'final': 2556,
 'tkts': 6954,
 '21st': 80,
 'text': 6823,
 'receive': 5550,
 'question': 5445,
 'std': 6463,
 'txt': 7136,
 'rate': 5497,
 'apply': 563,
 '08452810075over18': 6,
 'dun': 2173,
 'say': 5885,
 'early': 2192,
 'hor': 3250,
 'nah': 4527,
 'don': 2086,
 'think': 6878,
 'goes': 2893,
 'usf': 7272,
 'lives': 3970,
 'freemsg': 2707,
 'hey': 3167,
 'darling': 1821,
 'week': 7506,
 'word': 7653,
 'like': 3920,
 'fun': 2758,
 'tb': 6758,
 'xxx': 7727,
 'chgs': 1383,
 'send': 5971,
 'rcv': 5509,
 'brother': 1109,
 'speak': 6345,
 'treat': 7069,
 'aids': 420,
 'patent': 4981,
 'request': 5659,
 'melle': 4268,
 'oru': 4861,
 'minnaminunginte': 4333,
 'nurungu': 4717,
 'vettam': 7327,
 'set': 5997,
 'callertune': 1207,
 'callers': 1206,
 'press': 5297,
 'copy': 1646,
 'friends': 2723,
 'winner': 7592,
 'valued': 7297,
 'network': 4604,
 'customer': 1777,
 'selected': 5957,
 'receivea': 5551,
 'prize': 5329,
 'reward': 5714,
 'claim': 1435,
 'code': 1500,
 'kl341': 3747,
 'valid': 7293,
 'hours': 3270,
 'mobile': 4386,
 'months': 4426,
 'entitled': 2307,
 'update': 7236,
 'latest': 3833,
 'colour': 1521,
 'mobiles': 4387,
 'camera': 1219,
 'gonna': 2909,
 'home': 3224,
 'soon': 6299,
 'want': 7440,
 'talk': 6725,
 'stuff': 6552,
 'anymore': 534,
 'tonight': 7001,
 've': 7312,
 'cried': 1723,
 'today': 6973,
 'chances': 1324,
 'cash': 1270,
 'pounds': 5238,
 'csh11': 1741,
 'cost': 1658,
 '150p': 44,
 'day': 1836,
 '6days': 233,
 'tsandcs': 7104,
 'reply': 5652,
 'hl': 3196,
 'info': 3437,
 'urgent': 7253,
 'won': 7637,
 'membership': 4274,
 'jackpot': 3556,
 'www': 7709,
 'dbuk': 1841,
 'net': 4598,
 'lccltd': 3850,
 'pobox': 5155,
 '4403ldnw1a7rw18': 173,
 'searching': 5930,
 'right': 5726,
 'words': 7654,
 'thank': 6839,
 'breather': 1078,
 'promise': 5361,
 'wont': 7644,
 'help': 3147,
 'granted': 2958,
 'fulfil': 2755,
 'wonderful': 7641,
 'blessing': 956,
 'times': 6933,
 'date': 1829,
 'sunday': 6619,
 'xxxmobilemovieclub': 7728,
 'use': 7266,
 'credit': 1713,
 'click': 1458,
 'wap': 7445,
 'link': 3942,
 'message': 4292,
 'http': 3289,
 'com': 1524,
 'qjkgighjjgcbl': 5437,
 'oh': 4773,
 'watching': 7466,
 'eh': 2238,
 'remember': 5619,
 'spell': 6360,
 'yes': 7764,
 'did': 1967,
 'naughty': 4559,
 'make': 4151,
 'wet': 7541,
 'fine': 2563,
 'thatåõs': 6851,
 'way': 7478,
 'feel': 2511,
 'gota': 2930,
 'england': 2289,
 'macedonia': 4114,
 'dont': 2089,
 'miss': 4349,
 'goals': 2889,
 'team': 6770,
 'news': 4616,
 'ur': 7249,
 'national': 4553,
 'try': 7100,
 'wales': 7420,
 'scotland': 5909,
 '4txt': 196,
 'ì¼1': 7826,
 'poboxox36504w45wq': 5167,
 'seriously': 5990,
 'going': 2898,
 'ha': 3030,
 'ì_': 7825,
 'pay': 4993,
 'da': 1794,
 'stock': 6488,
 'comin': 1535,
 'aft': 394,
 'finish': 2566,
 'lunch': 4080,
 'str': 6513,
 'lor': 4024,
 'ard': 589,
 'smth': 6247,
 'ffffffffff': 2529,
 'alright': 466,
 'meet': 4257,
 'sooner': 6300,
 'just': 3661,
 'forced': 2654,
 'eat': 2204,
 'slice': 6199,
 'really': 5533,
 'hungry': 3308,
 'tho': 6893,
 'sucks': 6588,
 'mark': 4187,
 'getting': 2848,
 'worried': 7665,
 'knows': 3758,
 'sick': 6120,
 'turn': 7123,
 'pizza': 5111,
 'lol': 4001,
 'convincing': 1634,
 'catch': 1280,
 'bus': 1158,
 'frying': 2743,
 'egg': 2235,
 'tea': 6764,
 'eating': 2207,
 'mom': 4407,
 'left': 3872,
 'dinner': 1999,
 'love': 4045,
 'amp': 487,
 'packing': 4913,
 'car': 1242,
 'll': 3974,
 'let': 3892,
 'know': 3755,
 'room': 5767,
 'ahhh': 415,
 'work': 7655,
 'vaguely': 7289,
 'does': 2061,
 'wait': 7414,
 'clear': 1452,
 'sure': 6645,
 'sarcastic': 5865,
 'doesn': 2063,
 'live': 3966,
 'yeah': 7752,
 'apologetic': 550,
 'fallen': 2465,
 'actin': 336,
 'spoilt': 6387,
 'child': 1391,
 'caught': 1284,
 'till': 6930,
 'doing': 2076,
 'badly': 758,
 'cheers': 1367,
 'tell': 6788,
 'fear': 2503,
 'fainting': 2457,
 'housework': 3274,
 'quick': 5448,
 'cuppa': 1766,
 'thanks': 6840,
 'subscription': 6577,
 'ringtone': 5735,
 'uk': 7166,
 'charged': 1336,
 'month': 4423,
 'confirm': 1589,
 'replying': 5653,
 'yup': 7804,
 'look': 4012,
 'timings': 6937,
 'msg': 4461,
 'xuhui': 7723,
 'learn': 3863,
 '2nd': 117,
 'lesson': 3890,
 '8am': 259,
 'oops': 4817,
 'roommate': 5769,
 'letter': 3894,
 'decide': 1858,
 'hello': 3144,
 'saturday': 5877,
 'texting': 6831,
 'decided': 1859,
 'tomo': 6990,
 'trying': 7102,
 'invite': 3493,
 'pls': 5143,
 'ahead': 414,
 'watts': 7474,
 'wanted': 7442,
 'weekend': 7508,
 'abiola': 290,
 'forget': 2660,
 'need': 4579,
 'crave': 1703,
 'sweet': 6676,
 'arabian': 586,
 'steed': 6470,
 'mmmmmm': 4376,
 'yummy': 7799,
 'rodger': 5757,
 'burns': 1155,
 'tried': 7078,
 'sms': 6242,
 'nokia': 4660,
 'camcorder': 1217,
 'delivery': 1898,
 'tomorrow': 6992,
 'seeing': 5948,
 'hope': 3242,
 'man': 4161,
 'endowed': 2279,
 'lt': 4068,
 'gt': 2998,
 'inches': 3407,
 'calls': 1212,
 'messages': 4294,
 'missed': 4351,
 'didn': 1969,
 'hep': 3158,
 'immunisation': 3388,
 'nigeria': 4629,
 'fair': 2458,
 'hopefully': 3245,
 'tyler': 7149,
 'maybe': 4233,
 'ask': 638,
 'bit': 933,
 'stubborn': 6541,
 'hospital': 3257,
 'kept': 3704,
 'telling': 6789,
 'weak': 7483,
 'sucker': 6586,
 'hospitals': 3258,
 'suckers': 6587,
 'thinked': 6879,
 'time': 6932,
 'saw': 5884,
 'class': 1444,
 'gram': 2950,
 'usually': 7278,
 'runs': 5810,
 'half': 3045,
 'eighth': 2240,
 'smarter': 6222,
 'gets': 2844,
 'second': 5934,
 'fyi': 2773,
 'ride': 5725,
 'morning': 4433,
 'crashing': 1702,
 'place': 5113,
 'wow': 7680,
 'realized': 5531,
 'embarassed': 2261,
 'accomodations': 319,
 'thought': 6896,
 'liked': 3921,
 'best': 890,
 'happy': 3080,
 'cave': 1288,
 'sorry': 6309,
 'offered': 4759,
 'embarassing': 2262,
 'ac': 305,
 'sptv': 6409,
 'new': 4611,
 'jersey': 3597,
 'devils': 1948,
 'detroit': 1942,
 'red': 5573,
 'wings': 7590,
 'play': 5127,
 'ice': 3342,
 'hockey': 3209,
 'correct': 1651,
 'incorrect': 3418,
 'end': 2275,
 'mallika': 4160,
 'sherawat': 6047,
 'yesterday': 7766,
 'url': 7259,
 'congrats': 1595,
 'year': 7753,
 'special': 6347,
 'cinema': 1430,
 'pass': 4970,
 'suprman': 6643,
 'matrix3': 4220,
 'starwars3': 6451,
 'bx420': 1178,
 'ip4': 3502,
 '5we': 225,
 '150pm': 46,
 'later': 3832,
 'meeting': 4259,
 'reached': 5515,
 'gauti': 2807,
 'sehwag': 5954,
 'odi': 4753,
 'series': 5989,
 'pick': 5083,
 'burger': 1150,
 'pain': 4920,
 'killing': 3729,
 'good': 2911,
 'joke': 3623,
 'girls': 2866,
 'situation': 6166,
 'seekers': 5949,
 'checking': 1361,
 'iq': 3508,
 'roommates': 5770,
 'took': 7005,
 'forever': 2657,
 'come': 1530,
 'double': 2103,
 'check': 1357,
 'hair': 3040,
 'dresser': 2132,
 'said': 5836,
 'wun': 7708,
 'cut': 1781,
 'short': 6082,
 'nice': 4623,
 'pleased': 5136,
 'advise': 377,
 'following': 2636,
 'recent': 5554,
 'review': 5712,
 'mob': 4384,
 'awarded': 723,
 'bonus': 997,
 'song': 6294,
 'dedicated': 1869,
 'dedicate': 1868,
 'valuable': 7295,
 'frnds': 2731,
 'rply': 5786,
 'complimentary': 1564,
 'trip': 7079,
 'eurodisinc': 2352,
 'trav': 7061,
 'aco': 333,
 'entry41': 2311,
 'dis': 2011,
 'morefrmmob': 4430,
 'shracomorsglsuplt': 6105,
 'ls1': 4064,
 '3aj': 149,
 'hear': 3123,
 'divorce': 2040,
 'barbie': 789,
 'comes': 1532,
 'ken': 3702,
 'plane': 5119,
 'wah': 7407,
 'lucky': 4074,
 'save': 5880,
 'money': 4414,
 'hee': 3136,
 'finished': 2568,
 'hi': 3172,
 'babe': 745,
 'im': 3376,
 'wanna': 7438,
 'xx': 7724,
 'performed': 5029,
 'waiting': 7417,
 'machan': 4116,
 'thats': 6850,
 'cool': 1639,
 'gentleman': 2832,
 'dignity': 1989,
 'respect': 5679,
 'peoples': 5022,
 'shy': 6115,
 'pa': 4909,
 'operate': 4824,
 'looking': 4016,
 'job': 3612,
 'ta': 6703,
 'earn': 2193,
 'ah': 412,
 'stop': 6498,
 'urgnt': 7256,
 'real': 5524,
 'yo': 7775,
 'tickets': 6920,
 'jacket': 3555,
 'used': 7267,
 'multis': 4487,
 'started': 6446,
 'requests': 5660,
 'came': 1218,
 'bed': 853,
 'coins': 1506,
 'factory': 2447,
 'gotta': 2935,
 'nitros': 4647,
 'ela': 2244,
 'kano': 3684,
 'il': 3371,
 'download': 2110,
 'wen': 7525,
 'stand': 6434,
 'close': 1465,
 'night': 4631,
 'spent': 6365,
 'late': 3829,
 'afternoon': 396,
 'casualty': 1278,
 'means': 4246,
 'haven': 3102,
 'stuff42moro': 6553,
 'includes': 3411,
 'sheets': 6042,
 'smile': 6230,
 'pleasure': 5138,
 'trouble': 7086,
 'pours': 5240,
 'rain': 5471,
 'sum1': 6610,
 'hurts': 3318,
 'becoz': 851,
 'loves': 4053,
 'smiling': 6234,
 'service': 5993,
 'representative': 5657,
 '10am': 27,
 '9pm': 270,
 'guaranteed': 3001,
 'havent': 3103,
 'planning': 5123,
 'buy': 1169,
 'lido': 3905,
 'collected': 1515,
 'simply': 6141,
 'password': 4977,
 'mix': 4367,
 'verify': 7323,
 'usher': 7273,
 'britney': 1099,
 'fml': 2627,
 'telugu': 6794,
 'movie': 4450,
 'abt': 300,
 'loads': 3980,
 'loans': 3982,
 'wk': 7616,
 'hols': 3222,
 'run': 5808,
 'forgot': 2665,
 'hairdressers': 3042,
 'appointment': 566,
 'shower': 6098,
 'cause': 1285,
 'prob': 5334,
 'ham': 3051,
 'okay': 4779,
 'price': 5310,
 'long': 4008,
 'legal': 3875,
 'ave': 710,
 'ams': 491,
 'gone': 2907,
 '4the': 194,
 'driving': 2141,
 'test': 6817,
 'mean': 4242,
 'guess': 3007,
 'gave': 2808,
 'boston': 1018,
 'men': 4278,
 'changed': 1326,
 'search': 5929,
 'location': 3985,
 'nyc': 4728,
 'cuz': 1788,
 'signin': 6129,
 'page': 4916,
 'says': 5888,
 'umma': 7173,
 'life': 3908,
 'vava': 7309,
 'lot': 4032,
 'dear': 1848,
 'wishes': 7603,
 'birthday': 931,
 'making': 4155,
 'truly': 7095,
 'memorable': 4275,
 'aight': 422,
 'hit': 3189,
 'ip': 3501,
 'address': 354,
 'considering': 1607,
 'computer': 1570,
 'isn': 3525,
 'minecraft': 4327,
 'server': 5992,
 'grumpy': 2995,
 'old': 4791,
 'people': 5021,
 'better': 896,
 'lying': 4094,
 'jokes': 3625,
 'worry': 7667,
 'busy': 1164,
 'plural': 5147,
 'noun': 4696,
 'research': 5665,
 'cos': 1656,
 'things': 6877,
 'scared': 5894,
 'mah': 4138,
 'loud': 4040,
 'gent': 2830,
 'contact': 1612,
 'weekends': 7509,
 'draw': 2124,
 'shows': 6104,
 'k52': 3667,
 '12hrs': 38,
 '150ppm': 48,
 'wa': 7402,
 'openin': 4821,
 'sentence': 5982,
 'formal': 2669,
 'juz': 3666,
 'tt': 7110,
 'eatin': 2206,
 'puttin': 5426,
 'weight': 7514,
 'haha': 3036,
 'anythin': 538,
 'happened': 3072,
 'entered': 2300,
 'cabin': 1186,
 'boss': 1017,
 'felt': 2520,
 'askd': 639,
 'invited': 3494,
 'apartment': 544,
 'went': 7528,
 'specially': 6351,
 'holiday': 3219,
 'flights': 2603,
 'operator': 4825,
 '0871277810910p': 15,
 'min': 4321,
 'goodo': 2920,
 'friday': 2718,
 'potato': 5232,
 'ratio': 5499,
 'tortilla': 7021,
 'needed': 4581,
 'hmm': 3201,
 'uncle': 7181,
 'informed': 3440,
 'paying': 4998,
 'school': 5900,
 'directly': 2005,
 'food': 2643,
 'private': 5326,
 'account': 322,
 'statement': 6454,
 'unredeemed': 7224,
 'points': 5177,
 'identifier': 3354,
 'expires': 2418,
 'caller': 1205,
 'landline': 3807,
 'box42wr29c': 1042,
 'apples': 561,
 'pairs': 4924,
 'malarky': 4157,
 'todays': 6974,
 'voda': 7371,
 'numbers': 4714,
 'ending': 2277,
 'award': 722,
 'match': 4208,
 'quoting': 5459,
 'standard': 6435,
 'rates': 5498,
 'app': 554,
 'sao': 5859,
 'mu': 4477,
 'ìï': 7828,
 'predict': 5272,
 'buying': 1172,
 'yetunde': 7768,
 'hasn': 3092,
 'sent': 5981,
 'bother': 1020,
 'sending': 5973,
 'involve': 3498,
 'shouldn': 6092,
 'imposed': 3395,
 'apologise': 551,
 'girl': 2863,
 'del': 1888,
 'bak': 766,
 'sum': 6609,
 'lucyxx': 4077,
 'tmorrow': 6960,
 'accomodate': 318,
 'answer': 522,
 'sunshine': 6626,
 'quiz': 5455,
 'sony': 6296,
 'dvd': 2182,
 'player': 5129,
 'country': 1675,
 'algarve': 450,
 'ansr': 521,
 'sp': 6332,
 'tyrone': 7153,
 'laid': 3799,
 'dogging': 2070,
 'locations': 3986,
 'direct': 2004,
 'join': 3620,
 'largest': 3824,
 'bt': 1125,
 'txting': 7142,
 'gravel': 2963,
 'nt': 4704,
 'ec2a': 2209,
 '31p': 146,
 'haf': 3035,
 'msn': 4468,
 'yijue': 7772,
 'hotmail': 3265,
 'rooms': 5771,
 'befor': 862,
 'activities': 342,
 'msgs': 4467,
 'chat': 1347,
 'svc': 6661,
 'hardcore': 3082,
 'services': 5994,
 'age': 401,
 'yr': 7794,
 'lazy': 3849,
 'type': 7150,
 'lect': 3869,
 'pouch': 5235,
 'sir': 6155,
 'mail': 4143,
 'swt': 6690,
 'nver': 4722,
 'tired': 6940,
 'little': 3965,
 'lovable': 4044,
 'persons': 5046,
 'coz': 1688,
 'somtimes': 6291,
 'occupy': 4746,
 'biggest': 914,
 'hearts': 3129,
 'gud': 3003,
 'ni8': 4621,
 'open': 4818,
 'ya': 7737,
 'dot': 2102,
 'whats': 7546,
 'staff': 6426,
 'taking': 6722,
 'replied': 5650,
 'randy': 5491,
 'sexy': 6009,
 'female': 2521,
 'local': 3984,
 'luv': 4085,
 'netcollex': 4599,
 '08700621170150p': 8,
 'ummma': 7175,
 'begin': 866,
 'qatar': 5432,
 'pray': 5267,
 'hard': 3081,
 'deleted': 1892,
 'sindu': 6145,
 'birla': 927,
 'soft': 6268,
 'wine': 7588,
 'flowing': 2618,
 'nevering': 4608,
 'thk': 6887,
 'plaza': 5134,
 'typical': 7152,
 'dirt': 2008,
 'floor': 2612,
 'windows': 7585,
 'shirt': 6061,
 'mouth': 4447,
 'dream': 2127,
 'chores': 1418,
 'joy': 3638,
 'lots': 4034,
 'tv': 7128,
 'exist': 2403,
 'hail': 3039,
 'mist': 4359,
 'aaooooright': 280,
 'leaving': 3868,
 'house': 3271,
 'interview': 3481,
 'boy': 1047,
 'missing': 4353,
 'annoncement': 513,
 'years': 7754,
 'arrange': 615,
 'safe': 5831,
 'envy': 2316,
 'parents': 4953,
 'hand': 3054,
 'excited': 2391,
 'spend': 6363,
 'bootydelious': 1010,
 'inviting': 3495,
 'friend': 2722,
 'frnd': 2730,
 'bangbabes': 780,
 'order': 4846,
 'content': 1616,
 'goto': 2934,
 'bangb': 779,
 'internet': 3480,
 'menu': 4285,
 'cultures': 1760,
 'module': 4400,
 's89': 5821,
 'avoid': 716,
 'missunderstding': 4357,
 'wit': 7608,
 'beloved': 881,
 'escape': 2337,
 'fancy': 2476,
 'bridge': 1084,
 'needs': 4584,
 'lager': 3798,
 'completely': 1560,
 'form': 2668,
 'clark': 1441,
 'utter': 7280,
 'waste': 7458,
 'axis': 731,
 'bank': 782,
 'hmmm': 3202,
 'hop': 3241,
 'muz': 4511,
 'discuss': 2024,
 'liao': 3899,
 'coming': 1536,
 'bloody': 970,
 'hell': 3142,
 'believe': 872,
 'surname': 6651,
 'mr': 4456,
 'ill': 3373,
 'clue': 1481,
 'spanish': 6339,
 'begins': 867,
 'bath': 813,
 'carlos': 1259,
 'mall': 4159,
 'turns': 7126,
 'staying': 6461,
 'til': 6929,
 'smoke': 6236,
 'worth': 7671,
 'doesnt': 2064,
 'log': 3992,
 'spoke': 6388,
 'maneesha': 4171,
 'satisfied': 5874,
 'experience': 2413,
 'toll': 6986,
 'lifted': 3914,
 'hopes': 3247,
 'offer': 4758,
 'especially': 2341,
 'approaches': 570,
 'studying': 6550,
 'anyways': 541,
 'gr8': 2943,
 'trust': 7097,
 'guys': 3023,
 'bye': 1181,
 'handsome': 3060,
 'finding': 2561,
 'working': 7659,
 'mummy': 4491,
 'boytoy': 1052,
 'awesome': 725,
 'minute': 4338,
 'freephone': 2708,
 '9am': 268,
 '11pm': 34,
 'xmas': 7720,
 'radio': 5464,
 'jus': 3660,
 'bathe': 814,
 'sis': 6157,
 'using': 7274,
 'finishes': 2569,
 'unique': 7209,
 '30th': 145,
 'august': 692,
 'areyouunique': 595,
 'joined': 3621,
 'league': 3861,
 'touch': 7030,
 'deal': 1844,
 'personal': 5043,
 'finally': 2558,
 'completed': 1559,
 'course': 1681,
 'suggest': 6601,
 'stays': 6462,
 'able': 292,
 'ors': 4859,
 'stool': 6497,
 'settled': 6001,
 'wishin': 7604,
 'mrng': 4458,
 'hav': 3100,
 'story': 6512,
 'hamster': 3053,
 'dead': 1843,
 'tmr': 6961,
 '1pm': 65,
 'orchard': 4845,
 'mrt': 4459,
 'kate': 3689,
 'evening': 2358,
 'babyjontet': 750,
 'enc': 2274,
 'bucks': 1129,
 'darlin': 1820,
 'ive': 3541,
 'college': 1519,
 'refilled': 5583,
 'successfully': 6585,
 'inr': 3455,
 'decimal': 1861,
 'keralacircle': 3706,
 'prepaid': 5283,
 'balance': 769,
 'rs': 5788,
 'transaction': 7051,
 'id': 3348,
 'kr': 3772,
 'goodmorning': 2916,
 'sleeping': 6193,
 'ga': 2776,
 'alter': 468,
 'dat': 1827,
 'ericsson': 2324,
 'oso': 4864,
 'oredi': 4849,
 'dats': 1833,
 'straight': 6515,
 'dogg': 2068,
 'connection': 1600,
 'refund': 5588,
 'shoot': 6076,
 'big': 912,
 'ready': 5523,
 'bruv': 1120,
 'break': 1069,
 'rewarding': 5715,
 'semester': 5967,
 'study': 6549,
 'noe': 4654,
 'leh': 3878,
 'sounds': 6321,
 'heading': 3115,
 'prediction': 5275,
 'slept': 6198,
 'past': 4979,
 'nights': 4634,
 'easy': 2203,
 'sen': 5970,
 'exam': 2387,
 'march': 4182,
 'atm': 670,
 'register': 5596,
 'os': 4862,
 'called': 1204,
 ...}

In [12]:

print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in a wkly comp to win FA Cup final ...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried contact u. ...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder
X = data['v2'].to_numpy()
Y = data['v1'].to_numpy()

# Convert the labels to integers using LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(Y)

In [14]:
# Step 3: Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
#CountVectorizer the text data is converted into a numerical representation
from sklearn.feature_extraction.text import CountVectorizer
#Feature Extraction using CountVectorizer
vector = CountVectorizer()
X_train_count = vector.fit_transform(X_train)
X_test_count = vector.transform(X_test)

In [16]:
#calculate unique words in the vocabulary that has been learned by CountVectorizer from the training data
print(len(vector.vocabulary_))
#Gives the number of samples and the number of features
print(X_train_count.shape)
print(X_test_count.shape)

7735
(4457, 7735)
(1115, 7735)

In [17]:
from sklearn.naive_bayes import MultinomialNB

#Model Selection and Training (Naive Bayes)
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train_count, y_train)
y_pred = nb_classifier.predict(X_test_count)

In [18]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9838565022421525

In [19]:
from sklearn.metrics import classification_report

y_pred = nb_classifier.predict(X_test_count)
classification_rep = classification_report(y_test, y_pred)
print("Precission:")
print(classification_rep)

Precission:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       0.99      0.89      0.94       150

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115